parameters:
    lia.service.theme.class: Lia\ThemeBundle\DependencyInjection\Service

services:
    lia.service.theme:
        class: %lia.service.theme.class%
        calls:
            - ['setContainer', [@service_container]]
